<%--
  ~    Copyright 2003, 2004, 2005, 2006 Research Triangle Institute
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  --%>
<%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %>
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>
<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %>
<%@ taglib uri='/WEB-INF/struts-tiles.tld' prefix='template' %>
<%@ taglib uri='/WEB-INF/tlds/zeprs.tld' prefix='zeprs' %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<template:insert template='/WEB-INF/templates/template-admin.jsp'>
    <template:put name='title' content='Admin: Subscriptions' direct='true'/>
    <template:put name='header' content='Admin: Subscriptions' direct='true'/>
    <template:put name='content' direct='true'>
        <script type='text/javascript'
                src='/zeprs/js/engine2.jsp;jsessionid=${pageContext.request.session.id}'></script>
        <script type='text/javascript'
                src='/zeprs/dwrdyna/util.js;jsessionid=${pageContext.request.session.id}'></script>
        <script type='text/javascript'
                src='/zeprs/dwrdyna/interface/Dynasite.js;jsessionid=${pageContext.request.session.id}'></script>
        <html:errors/>
        <c:if test="${! empty message}">
             <p class="bold">${message}</p>
        </c:if>
        <c:if test="${! empty generateStatusDate}">
            <p class="error">System is currently processing or generating a feed.<c:if test="${! empty statusMessage}"> Status: ${statusMessage}</c:if></p>
            </c:if>
        <p><html:link action="/admin/publisher/new">Site Publisher Setup</html:link></p>
        <div>
            <p>Site rss feed URL must begin with <strong>http://</strong></p>
            <html:form action="admin/subscription/save" method="POST">
                <div class="row">
                    <span class="label">Site rss feed URL:</span>
                    <span class="formw"><html:text property="url" size="60"/><html:submit value="Save"/></span>
                </div>
            </html:form>
        </div>
        <c:if test="${! empty subscriptions}">
            <div class="row" style="width:600px; padding-top: 5px;">
                <p class="bold">Instructions</p>
                <ul>
                <li>If you just subscribed to a feed, click "Import" in the first column to initiate the first sync. </li>
                <li>Clicking "Update" in the first column will import any new patients from the remote site to the
                    current ZEPRS installation. </li>
                    <li>Clicking "Update sitename" in the "Reload" column will compare all of the patient records from the remote
                    site. This choice takes much longer. You normally do not need to do this, since the system
                    automatically performs the import. </li>
                    <li>Clicking "Compare" compares the master database with the xml files generated by the remote system.</li>
                    <li>Paste the Patient's district id (5040-192-xxxxx-x) in the Patient box to reload a patient's record.</li>
                    <li>If you delete a subscription before it has completed its first import, the update log will not be deleted for that site.</li>
                    </ul>
               <p class="bold">Current subscriptions</p>
                <table class="enhancedtable">
                    <tr>
                        <th>Site</th>
                        <th>RSS file</th>
                        <th>Record listing</th>
                        <th>Reload</th>
                        <th>Compare w/ master</th>
                        <th>Patient</th>
                        <th>Delete</th>
                    </tr>
                    <c:forEach items="${subscriptions}" var="subscription">
                        <c:url value="admin/import.do" var="updateLink"><c:param name="url" value="${subscription.url}"/><c:param name="subscriptionId" value="${subscription.id}"/></c:url>
                        <c:url value="admin/import.do" var="reloadLink"><c:param name="url" value="${subscription.url}"/><c:param name="subscriptionId" value="${subscription.id}"/><c:param name="reload" value="1"/></c:url>
                        <c:url value="admin/import.do" var="importMissingLink"><c:param name="url" value="${subscription.url}"/><c:param name="subscriptionId" value="${subscription.id}"/><c:param name="reload" value="2"/></c:url>
                        <c:url value="admin/import.do" var="importLink"><c:param name="url" value="${subscription.url}"/><c:param name="subscriptionId" value="${subscription.id}"/><c:param name="start" value="1"/></c:url>
                        <c:url value="admin/import.do" var="viewLink"><c:param name="url" value="${subscription.url}"/><c:param name="view" value="1"/><c:param name="subscriptionId" value="${subscription.id}"/></c:url>
                        <tr>
                            <td>
                                <c:choose>
                                    <c:when test="${ ! empty subscription.site}"><a href='<c:out value="/zeprs/${updateLink}"/>'>Update ${subscription.site}</a></c:when>
                                    <c:otherwise><a href='<c:out value="/zeprs/${importLink}"/>'>Import</a></c:otherwise>
                                </c:choose></td>
                            <td><a href="${subscription.url}">${subscription.url}</a></td>
                            <td><a href='<c:out value="/zeprs/${viewLink}"/>'>Patients</a></td>
                            <td><a href='<c:out value="/zeprs/${reloadLink}"/>'>Update ${subscription.site}</a></td>
                            <td><a href='<c:out value="/${appName}/${importMissingLink}"/>'>Import Missing ${subscription.site} patients</a></td>
                            <td>
                                <html:form action="/admin/compareDatabases">
                                <input type="hidden" name="siteAbbrev" value="${subscription.site}"/>
                                <input type="hidden" name="url" value="${subscription.url}"/>
						<table class="enhancedtable">
							<tr><th>Begin date</th><th>End date</th><th>&nbsp</th></tr>
							<tr>
								<td><zeprs:date_visit_no_form_no_label
									element="chooseReportForm" dateVisit="${date1daypast}"
									field="bdate|bdate1" /></td>

								<td><zeprs:date_visit_no_form_no_label
									element="chooseReportForm" dateVisit="${date1DayFuture}"
									field="edate|edate1" /></td>
								<td><html:submit/></td>
							</tr>
						</table>
						</html:form></td>
                            <td><input type="text" id="patientId" onchange="importPatient('${subscription.url}', '${pageContext.request.session.id}')"/></td>
                            <td><html:link action="/admin/subscription/delete" paramId="id" paramName="subscription" paramProperty="id" onclick="return confirm('Caution: Are you sure you want to delete this subscription?');self.close();">X</html:link></td>
                        </tr>
                    </c:forEach>
                </table>
            </div>
        </c:if>
         <c:if test="${! empty logs}">
             <div class="row">
                  <p class="bold">Update log</p>
                  <p>Log of record imports</p>
                  <table class="enhancedtable" width="800px">
                    <tr>
                        <th>Updated</th>
                        <th>RSS file Build Date</th>
                        <th>Site</th>
                        <th>Comments</th>
                    </tr>
                    <c:forEach items="${logs}" var="log">
                        <tr>
                            <td>${log.updated}</td>
                            <td>${log.builddate}</td>
                            <td>${log.site}</td>
                            <td>${log.comments}</td>
                        </tr>
                    </c:forEach>
                </table>
             </div>
         </c:if>
    </template:put>
</template:insert>