/*
 *    Copyright 2003, 2004, 2005, 2006 Research Triangle Institute
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 */

package org.cidrz.project.zeprs.valueobject;

import java.sql.Date;
import java.sql.Time;

/**
 * JavaBean IntraLabourEval generated from database;
 * generated by DynasiteSourceGenerator, inspired by XslBeanGenerator by Klaus Berg.
 *
 * @author Chris Kelley
 */

/**
 * @hibernate.joined-subclass table="intralaboureval"
 * @hibernate.joined-subclass-key column="id"
 */
public class IntraLabourEval extends EncounterData {

private Time field1175;
private Integer field314;
private Integer field313;
private Integer field317;
private Integer field316;
private boolean field1221;
private Integer field330;
private Date field328;
private Time field329;
private Integer field331;
private Integer field325;
private Integer field326;
private Integer field327;
private Integer field339;
private String field337;
private Integer field336;
private Integer field338;
private String field324;
private Integer field340;
private Integer field1341;
private Integer field242;
private Integer field243;
private Integer field244;
private Integer field1136;
private Integer field1137;
private Integer field1138;
private Integer field1139;
private Integer field1140;
private Integer field1141;
private Integer field1142;
private Integer field1143;
private Integer field1144;
private Integer field1145;
private String field1146;


 /**
  * @return
  * @hibernate.property column="time_of_exam_1175"
  */
    public Time getfield1175() {
        return this.field1175;
    }

    public void setfield1175(Time field1175) {
        this.field1175 = field1175;
    }



 /**
  * @return
  * @hibernate.property column="presentation_314"
  */
    public Integer getfield314() {
        return this.field314;
    }

    public void setfield314(Integer field314) {
        this.field314 = field314;
    }



 /**
  * @return
  * @hibernate.property column="lie_313"
  */
    public Integer getfield313() {
        return this.field313;
    }

    public void setfield313(Integer field313) {
        this.field313 = field313;
    }



 /**
  * @return
  * @hibernate.property column="contraction_freq_10_abd_palp_317"
  */
    public Integer getfield317() {
        return this.field317;
    }

    public void setfield317(Integer field317) {
        this.field317 = field317;
    }



 /**
  * @return
  * @hibernate.property column="contraction_strength_316"
  */
    public Integer getfield316() {
        return this.field316;
    }

    public void setfield316(Integer field316) {
        this.field316 = field316;
    }



 /**
  * @return
  * @hibernate.property column="rupture_of_membranes_1221"
  */
    public boolean isfield1221() {
        return this.field1221;
    }

    public void setfield1221(boolean field1221) {
        this.field1221 =  field1221;
    }



 /**
  * @return
  * @hibernate.property column="membranes_re_330"
  */
    public Integer getfield330() {
        return this.field330;
    }

    public void setfield330(Integer field330) {
        this.field330 = field330;
    }



 /**
  * @return
  * @hibernate.property column="rupture_of_membranes_date_328"
  */
    public Date getfield328() {
        return this.field328;
    }

    public void setfield328(Date field328) {
        this.field328 = field328;
    }



 /**
  * @return
  * @hibernate.property column="rupture_of_membranes_time_329"
  */
    public Time getfield329() {
        return this.field329;
    }

    public void setfield329(Time field329) {
        this.field329 = field329;
    }



 /**
  * @return
  * @hibernate.property column="liquor_331"
  */
    public Integer getfield331() {
        return this.field331;
    }

    public void setfield331(Integer field331) {
        this.field331 = field331;
    }



 /**
  * @return
  * @hibernate.property column="cervix_dilatation325"
  */
    public Integer getfield325() {
        return this.field325;
    }

    public void setfield325(Integer field325) {
        this.field325 = field325;
    }



 /**
  * @return
  * @hibernate.property column="cervix_effacement_326"
  */
    public Integer getfield326() {
        return this.field326;
    }

    public void setfield326(Integer field326) {
        this.field326 = field326;
    }



 /**
  * @return
  * @hibernate.property column="cervix_consistency_327"
  */
    public Integer getfield327() {
        return this.field327;
    }

    public void setfield327(Integer field327) {
        this.field327 = field327;
    }



 /**
  * @return
  * @hibernate.property column="caput_339"
  */
    public Integer getfield339() {
        return this.field339;
    }

    public void setfield339(Integer field339) {
        this.field339 = field339;
    }



 /**
  * @return
  * @hibernate.property column="position_337"
  */
    public String getfield337() {
        return this.field337;
    }

    public void setfield337(String field337) {
        this.field337 = field337;
    }



 /**
  * @return
  * @hibernate.property column="station_of_pp_336"
  */
    public Integer getfield336() {
        return this.field336;
    }

    public void setfield336(Integer field336) {
        this.field336 = field336;
    }



 /**
  * @return
  * @hibernate.property column="moulding_338"
  */
    public Integer getfield338() {
        return this.field338;
    }

    public void setfield338(Integer field338) {
        this.field338 = field338;
    }



 /**
  * @return
  * @hibernate.property column="condition_of_vagina_other_324"
  */
    public String getfield324() {
        return this.field324;
    }

    public void setfield324(String field324) {
        this.field324 = field324;
    }



 /**
  * @return
  * @hibernate.property column="cord_at_vaginal_exam_340"
  */
    public Integer getfield340() {
        return this.field340;
    }

    public void setfield340(Integer field340) {
        this.field340 = field340;
    }



 /**
  * @return
  * @hibernate.property column="fetal_heart_rate"
  */
    public Integer getfield1341() {
        return this.field1341;
    }

    public void setfield1341(Integer field1341) {
        this.field1341 = field1341;
    }



 /**
  * @return
  * @hibernate.property column="urinalysis_alb_242"
  */
    public Integer getfield242() {
        return this.field242;
    }

    public void setfield242(Integer field242) {
        this.field242 = field242;
    }



 /**
  * @return
  * @hibernate.property column="urinalysis_glu_243"
  */
    public Integer getfield243() {
        return this.field243;
    }

    public void setfield243(Integer field243) {
        this.field243 = field243;
    }



 /**
  * @return
  * @hibernate.property column="urinalysis_ace_244"
  */
    public Integer getfield244() {
        return this.field244;
    }

    public void setfield244(Integer field244) {
        this.field244 = field244;
    }



 /**
  * @return
  * @hibernate.property column="drug_1_1136"
  */
    public Integer getfield1136() {
        return this.field1136;
    }

    public void setfield1136(Integer field1136) {
        this.field1136 = field1136;
    }



 /**
  * @return
  * @hibernate.property column="drug_2_1137"
  */
    public Integer getfield1137() {
        return this.field1137;
    }

    public void setfield1137(Integer field1137) {
        this.field1137 = field1137;
    }



 /**
  * @return
  * @hibernate.property column="drug_3_1138"
  */
    public Integer getfield1138() {
        return this.field1138;
    }

    public void setfield1138(Integer field1138) {
        this.field1138 = field1138;
    }



 /**
  * @return
  * @hibernate.property column="drug_4_1139"
  */
    public Integer getfield1139() {
        return this.field1139;
    }

    public void setfield1139(Integer field1139) {
        this.field1139 = field1139;
    }



 /**
  * @return
  * @hibernate.property column="drug_5_1140"
  */
    public Integer getfield1140() {
        return this.field1140;
    }

    public void setfield1140(Integer field1140) {
        this.field1140 = field1140;
    }



 /**
  * @return
  * @hibernate.property column="drug_6_1141"
  */
    public Integer getfield1141() {
        return this.field1141;
    }

    public void setfield1141(Integer field1141) {
        this.field1141 = field1141;
    }



 /**
  * @return
  * @hibernate.property column="drug_7_1142"
  */
    public Integer getfield1142() {
        return this.field1142;
    }

    public void setfield1142(Integer field1142) {
        this.field1142 = field1142;
    }



 /**
  * @return
  * @hibernate.property column="drug_8_1143"
  */
    public Integer getfield1143() {
        return this.field1143;
    }

    public void setfield1143(Integer field1143) {
        this.field1143 = field1143;
    }



 /**
  * @return
  * @hibernate.property column="drug_9_1144"
  */
    public Integer getfield1144() {
        return this.field1144;
    }

    public void setfield1144(Integer field1144) {
        this.field1144 = field1144;
    }



 /**
  * @return
  * @hibernate.property column="drug_10_1145"
  */
    public Integer getfield1145() {
        return this.field1145;
    }

    public void setfield1145(Integer field1145) {
        this.field1145 = field1145;
    }



 /**
  * @return
  * @hibernate.property column="current_medicine_1146"
  */
    public String getfield1146() {
        return this.field1146;
    }

    public void setfield1146(String field1146) {
        this.field1146 = field1146;
    }



}
