/*
 *    Copyright 2003, 2004, 2005, 2006 Research Triangle Institute
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 */

package org.cidrz.project.zeprs.valueobject;

import java.sql.Date;

/**
 * JavaBean PuerComp generated from database;
 * generated by DynasiteSourceGenerator, inspired by XslBeanGenerator by Klaus Berg.
 *
 * @author Chris Kelley
 */

/**
 * @hibernate.joined-subclass table="puercomp"
 * @hibernate.joined-subclass-key column="id"
 */
public class PuerComp extends EncounterData {

private Integer field601;
private Date field1268;
private Integer field1269;
private boolean field1270;
private boolean field1271;
private boolean field1272;
private boolean field1273;
private boolean field1274;
private boolean field1275;
private boolean field1276;
private boolean field1297;
private boolean field1277;
private String field1359;
private boolean field1279;
private boolean field1280;
private boolean field1281;
private boolean field1282;
private boolean field1283;
private String field1284;
private boolean field1285;
private boolean field1286;
private boolean field1287;
private boolean field1288;
private boolean field1289;
private boolean field1290;
private String field1291;
private String field1292;
private Float field266;
private Integer field171;
private Integer field167;
private String field1449;
private Integer field269;
private Integer field224;
private Integer field225;
private Date field1293;
private String field1213;


 /**
  * @return
  * @hibernate.property column="postnatal_visit_601"
  */
    public Integer getfield601() {
        return this.field601;
    }

    public void setfield601(Integer field601) {
        this.field601 = field601;
    }



 /**
  * @return
  * @hibernate.property column="date_of_discharge_1268"
  */
    public Date getfield1268() {
        return this.field1268;
    }

    public void setfield1268(Date field1268) {
        this.field1268 = field1268;
    }



 /**
  * @return
  * @hibernate.property column="hospital_ward_1269"
  */
    public Integer getfield1269() {
        return this.field1269;
    }

    public void setfield1269(Integer field1269) {
        this.field1269 = field1269;
    }



 /**
  * @return
  * @hibernate.property column="anaemia"
  */
    public boolean isfield1270() {
        return this.field1270;
    }

    public void setfield1270(boolean field1270) {
        this.field1270 =  field1270;
    }



 /**
  * @return
  * @hibernate.property column="diabetes_gestational"
  */
    public boolean isfield1271() {
        return this.field1271;
    }

    public void setfield1271(boolean field1271) {
        this.field1271 =  field1271;
    }



 /**
  * @return
  * @hibernate.property column="diabetes_pregestational"
  */
    public boolean isfield1272() {
        return this.field1272;
    }

    public void setfield1272(boolean field1272) {
        this.field1272 =  field1272;
    }



 /**
  * @return
  * @hibernate.property column="cardiac_disease"
  */
    public boolean isfield1273() {
        return this.field1273;
    }

    public void setfield1273(boolean field1273) {
        this.field1273 =  field1273;
    }



 /**
  * @return
  * @hibernate.property column="dysentary"
  */
    public boolean isfield1274() {
        return this.field1274;
    }

    public void setfield1274(boolean field1274) {
        this.field1274 =  field1274;
    }



 /**
  * @return
  * @hibernate.property column="epilepsy"
  */
    public boolean isfield1275() {
        return this.field1275;
    }

    public void setfield1275(boolean field1275) {
        this.field1275 =  field1275;
    }



 /**
  * @return
  * @hibernate.property column="gastroenteritis"
  */
    public boolean isfield1276() {
        return this.field1276;
    }

    public void setfield1276(boolean field1276) {
        this.field1276 =  field1276;
    }



 /**
  * @return
  * @hibernate.property column="hemoglobinopathy_sickle"
  */
    public boolean isfield1297() {
        return this.field1297;
    }

    public void setfield1297(boolean field1297) {
        this.field1297 =  field1297;
    }



 /**
  * @return
  * @hibernate.property column="diagnosis_other"
  */
    public boolean isfield1277() {
        return this.field1277;
    }

    public void setfield1277(boolean field1277) {
        this.field1277 =  field1277;
    }



 /**
  * @return
  * @hibernate.property column="diag_other"
  */
    public String getfield1359() {
        return this.field1359;
    }

    public void setfield1359(String field1359) {
        this.field1359 = field1359;
    }



 /**
  * @return
  * @hibernate.property column="antibiotics"
  */
    public boolean isfield1279() {
        return this.field1279;
    }

    public void setfield1279(boolean field1279) {
        this.field1279 =  field1279;
    }



 /**
  * @return
  * @hibernate.property column="analgesics"
  */
    public boolean isfield1280() {
        return this.field1280;
    }

    public void setfield1280(boolean field1280) {
        this.field1280 =  field1280;
    }



 /**
  * @return
  * @hibernate.property column="iron_supplimentation"
  */
    public boolean isfield1281() {
        return this.field1281;
    }

    public void setfield1281(boolean field1281) {
        this.field1281 =  field1281;
    }



 /**
  * @return
  * @hibernate.property column="misoprostal"
  */
    public boolean isfield1282() {
        return this.field1282;
    }

    public void setfield1282(boolean field1282) {
        this.field1282 =  field1282;
    }



 /**
  * @return
  * @hibernate.property column="med_treatments_other"
  */
    public boolean isfield1283() {
        return this.field1283;
    }

    public void setfield1283(boolean field1283) {
        this.field1283 =  field1283;
    }



 /**
  * @return
  * @hibernate.property column="med_treatments_other_desc"
  */
    public String getfield1284() {
        return this.field1284;
    }

    public void setfield1284(String field1284) {
        this.field1284 = field1284;
    }



 /**
  * @return
  * @hibernate.property column="mva"
  */
    public boolean isfield1285() {
        return this.field1285;
    }

    public void setfield1285(boolean field1285) {
        this.field1285 =  field1285;
    }



 /**
  * @return
  * @hibernate.property column="dilatation_and_curettage"
  */
    public boolean isfield1286() {
        return this.field1286;
    }

    public void setfield1286(boolean field1286) {
        this.field1286 =  field1286;
    }



 /**
  * @return
  * @hibernate.property column="laparotomy"
  */
    public boolean isfield1287() {
        return this.field1287;
    }

    public void setfield1287(boolean field1287) {
        this.field1287 =  field1287;
    }



 /**
  * @return
  * @hibernate.property column="hysterectomy"
  */
    public boolean isfield1288() {
        return this.field1288;
    }

    public void setfield1288(boolean field1288) {
        this.field1288 =  field1288;
    }



 /**
  * @return
  * @hibernate.property column="salpingostomy"
  */
    public boolean isfield1289() {
        return this.field1289;
    }

    public void setfield1289(boolean field1289) {
        this.field1289 =  field1289;
    }



 /**
  * @return
  * @hibernate.property column="surg_treat_other"
  */
    public boolean isfield1290() {
        return this.field1290;
    }

    public void setfield1290(boolean field1290) {
        this.field1290 =  field1290;
    }



 /**
  * @return
  * @hibernate.property column="surg_treat_other_desc"
  */
    public String getfield1291() {
        return this.field1291;
    }

    public void setfield1291(String field1291) {
        this.field1291 = field1291;
    }



 /**
  * @return
  * @hibernate.property column="medications_discharge"
  */
    public String getfield1292() {
        return this.field1292;
    }

    public void setfield1292(String field1292) {
        this.field1292 = field1292;
    }



 /**
  * @return
  * @hibernate.property column="temperature_266"
  */
    public Float getfield266() {
        return this.field266;
    }

    public void setfield266(Float field266) {
        this.field266 = field266;
    }



 /**
  * @return
  * @hibernate.property column="pulse_171"
  */
    public Integer getfield171() {
        return this.field171;
    }

    public void setfield171(Integer field171) {
        this.field171 = field171;
    }



 /**
  * @return
  * @hibernate.property column="respiratory_system_167"
  */
    public Integer getfield167() {
        return this.field167;
    }

    public void setfield167(Integer field167) {
        this.field167 = field167;
    }



 /**
  * @return
  * @hibernate.property column="respiratory_system_other"
  */
    public String getfield1449() {
        return this.field1449;
    }

    public void setfield1449(String field1449) {
        this.field1449 = field1449;
    }



 /**
  * @return
  * @hibernate.property column="respiration_rate_269"
  */
    public Integer getfield269() {
        return this.field269;
    }

    public void setfield269(Integer field269) {
        this.field269 = field269;
    }



 /**
  * @return
  * @hibernate.property column="bp_systolic_224"
  */
    public Integer getfield224() {
        return this.field224;
    }

    public void setfield224(Integer field224) {
        this.field224 = field224;
    }



 /**
  * @return
  * @hibernate.property column="bp_diastolic_225"
  */
    public Integer getfield225() {
        return this.field225;
    }

    public void setfield225(Integer field225) {
        this.field225 = field225;
    }



 /**
  * @return
  * @hibernate.property column="scheduled_followup_1293"
  */
    public Date getfield1293() {
        return this.field1293;
    }

    public void setfield1293(Date field1293) {
        this.field1293 = field1293;
    }



 /**
  * @return
  * @hibernate.property column="place_of_next_visit_1213"
  */
    public String getfield1213() {
        return this.field1213;
    }

    public void setfield1213(String field1213) {
        this.field1213 = field1213;
    }



}
