/*
 *    Copyright 2003, 2004, 2005, 2006 Research Triangle Institute
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 */

package org.cidrz.project.zeprs.valueobject;

import java.sql.Date;
import java.sql.Time;

/**
 * JavaBean VaginalExam generated from database;
 * generated by DynasiteSourceGenerator, inspired by XslBeanGenerator by Klaus Berg.
 *
 * @author Chris Kelley
 */

/**
 * @hibernate.joined-subclass table="vaginalexam"
 * @hibernate.joined-subclass-key column="id"
 */
public class VaginalExam extends EncounterData {

private Time field320;
private Integer field321;
private String field322;
private Integer field323;
private String field324;
private Integer field325;
private Integer field326;
private Integer field327;
private boolean field1221;
private Date field328;
private Time field329;
private Integer field330;
private Integer field331;
private Integer field314;
private String field1508;
private Integer field335;
private Integer field336;
private String field337;
private Integer field338;
private Integer field339;
private Integer field340;


 /**
  * @return
  * @hibernate.property column="time_320"
  */
    public Time getfield320() {
        return this.field320;
    }

    public void setfield320(Time field320) {
        this.field320 = field320;
    }



 /**
  * @return
  * @hibernate.property column="condition_of_vulva_321"
  */
    public Integer getfield321() {
        return this.field321;
    }

    public void setfield321(Integer field321) {
        this.field321 = field321;
    }



 /**
  * @return
  * @hibernate.property column="condition_of_vulva_desc_322"
  */
    public String getfield322() {
        return this.field322;
    }

    public void setfield322(String field322) {
        this.field322 = field322;
    }



 /**
  * @return
  * @hibernate.property column="condition_of_vagina_323"
  */
    public Integer getfield323() {
        return this.field323;
    }

    public void setfield323(Integer field323) {
        this.field323 = field323;
    }



 /**
  * @return
  * @hibernate.property column="condition_of_vagina_other_324"
  */
    public String getfield324() {
        return this.field324;
    }

    public void setfield324(String field324) {
        this.field324 = field324;
    }



 /**
  * @return
  * @hibernate.property column="cervix_dilatation325"
  */
    public Integer getfield325() {
        return this.field325;
    }

    public void setfield325(Integer field325) {
        this.field325 = field325;
    }



 /**
  * @return
  * @hibernate.property column="cervix_effacement_326"
  */
    public Integer getfield326() {
        return this.field326;
    }

    public void setfield326(Integer field326) {
        this.field326 = field326;
    }



 /**
  * @return
  * @hibernate.property column="cervix_consistency_327"
  */
    public Integer getfield327() {
        return this.field327;
    }

    public void setfield327(Integer field327) {
        this.field327 = field327;
    }



 /**
  * @return
  * @hibernate.property column="rupture_of_membranes_1221"
  */
    public boolean isfield1221() {
        return this.field1221;
    }

    public void setfield1221(boolean field1221) {
        this.field1221 =  field1221;
    }



 /**
  * @return
  * @hibernate.property column="rupture_of_membranes_date_328"
  */
    public Date getfield328() {
        return this.field328;
    }

    public void setfield328(Date field328) {
        this.field328 = field328;
    }



 /**
  * @return
  * @hibernate.property column="rupture_of_membranes_time_329"
  */
    public Time getfield329() {
        return this.field329;
    }

    public void setfield329(Time field329) {
        this.field329 = field329;
    }



 /**
  * @return
  * @hibernate.property column="membranes_re_330"
  */
    public Integer getfield330() {
        return this.field330;
    }

    public void setfield330(Integer field330) {
        this.field330 = field330;
    }



 /**
  * @return
  * @hibernate.property column="liquor_331"
  */
    public Integer getfield331() {
        return this.field331;
    }

    public void setfield331(Integer field331) {
        this.field331 = field331;
    }



 /**
  * @return
  * @hibernate.property column="presentation_314"
  */
    public Integer getfield314() {
        return this.field314;
    }

    public void setfield314(Integer field314) {
        this.field314 = field314;
    }



 /**
  * @return
  * @hibernate.property column="presentation_other"
  */
    public String getfield1508() {
        return this.field1508;
    }

    public void setfield1508(String field1508) {
        this.field1508 = field1508;
    }



 /**
  * @return
  * @hibernate.property column="presentation_obtained_by_335"
  */
    public Integer getfield335() {
        return this.field335;
    }

    public void setfield335(Integer field335) {
        this.field335 = field335;
    }



 /**
  * @return
  * @hibernate.property column="station_of_pp_336"
  */
    public Integer getfield336() {
        return this.field336;
    }

    public void setfield336(Integer field336) {
        this.field336 = field336;
    }



 /**
  * @return
  * @hibernate.property column="position_337"
  */
    public String getfield337() {
        return this.field337;
    }

    public void setfield337(String field337) {
        this.field337 = field337;
    }



 /**
  * @return
  * @hibernate.property column="moulding_338"
  */
    public Integer getfield338() {
        return this.field338;
    }

    public void setfield338(Integer field338) {
        this.field338 = field338;
    }



 /**
  * @return
  * @hibernate.property column="caput_339"
  */
    public Integer getfield339() {
        return this.field339;
    }

    public void setfield339(Integer field339) {
        this.field339 = field339;
    }



 /**
  * @return
  * @hibernate.property column="cord_at_vaginal_exam_340"
  */
    public Integer getfield340() {
        return this.field340;
    }

    public void setfield340(Integer field340) {
        this.field340 = field340;
    }



}
