/*
 *    Copyright 2003, 2004, 2005, 2006 Research Triangle Institute
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 */

/* Generated by Together */

package org.cidrz.webapp.dynasite.rules.impl;

import org.cidrz.webapp.dynasite.rules.Outcome;
import org.cidrz.webapp.dynasite.valueobject.Form;

/**
 * This Outcome drives the user to participate in another Encounter by requiring another form to be submitted..
 *
 * @hibernate.subclass discriminator-value="encounter"
 */
public class EncounterOutcome extends Outcome {

    private Integer requiredFormId;
    private Form requiredForm;

    /**
     * @return The Id of the Form which is required to be completed.
     * @hibernate.property column="required_form_id"
     */
    public Integer getRequiredFormId() {
        return requiredFormId;
    }

    /**
     * Sets the form id for the Encounter that is required. One can either set the form or the form_id.
     *
     * @param requiredFormId
     */
    public void setRequiredFormId(Integer requiredFormId) {
        this.requiredFormId = requiredFormId;
    }


}
