/*
 *    Copyright 2003, 2004, 2005, 2006 Research Triangle Institute
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 */

/* Generated by Together */

package org.cidrz.webapp.dynasite.rules.impl;

import org.cidrz.webapp.dynasite.rules.Outcome;

import java.sql.Date;


/**
 * @hibernate.subclass discriminator-value="referral"
 */
public class ReferralOutcome extends Outcome {
    private String reason;
    private String priority;
    private String transport;
    private Date uthAdmissionDate;
    private String arrivalCondition;
    private Integer uthWardId;

    /**
     * @return
     * @hibernate.property
     */
    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * @return
     * @hibernate.property column="priority_of_referral"
     */
    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    /**
     * @return
     * @hibernate.property column="transport"
     */

    public String getTransport() {
        return transport;
    }

    public void setTransport(String transport) {
        this.transport = transport;
    }

    /**
     * @return
     * @hibernate.property column="uth_admission_date"
     */

    public Date getUthAdmissionDate() {
        return uthAdmissionDate;
    }

    public void setUthAdmissionDate(Date uthAdmissionDate) {
        this.uthAdmissionDate = uthAdmissionDate;
    }

    /**
     * @return
     * @hibernate.property column="arrival_condition"
     */
    public String getArrivalCondition() {
        return arrivalCondition;
    }

    public void setArrivalCondition(String arrivalCondition) {
        this.arrivalCondition = arrivalCondition;
    }

        /**
     * @return
     * @hibernate.property column="uth_ward_id"
     */
    public Integer getUthWardId() {
        return uthWardId;
    }

    public void setUthWardId(Integer uthWardId) {
        this.uthWardId = uthWardId;
    }

}
