package org.rti.zcore;

import org.cidrz.project.zeprs.valueobject.EncounterData;


/**
 * Copied from JavaBean UserInfo generated from database;
 * generated by DynasiteSourceGenerator, inspired by XslBeanGenerator by Klaus Berg.
 *
 * @author Chris Kelley
 *         Date: 2010-02-16
 *         Time: 12:42:29
 *         Form Name: User Data
 *         Form Id: 223
 *Imported Form Id: 170
 */

/**
 * @hibernate.joined-subclass table="user_info"
 * @hibernate.joined-subclass-key column="id"
 */
public class UserInfo extends EncounterData {

private String username;	//username
private String password;	//password
private String email;	//email
private String forenames;	//forenames
private String lastname;	//lastname
private String mobile;	//mobile
private String phone;	//phone


 /**
  * @return
  * @hibernate.property column="username"
  */
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }





 /**
  * @return
  * @hibernate.property column="password"
  */
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }





 /**
  * @return
  * @hibernate.property column="email"
  */
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }





 /**
  * @return
  * @hibernate.property column="forenames"
  */
    public String getForenames() {
        return this.forenames;
    }

    public void setForenames(String forenames) {
        this.forenames = forenames;
    }





 /**
  * @return
  * @hibernate.property column="lastname"
  */
    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }





 /**
  * @return
  * @hibernate.property column="mobile"
  */
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }





 /**
  * @return
  * @hibernate.property column="phone"
  */
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }





}
